import 'package:json_annotation/json_annotation.dart';
import "user.dart";
part 'repo.g.dart';

@JsonSerializable()
class Repo {
    Repo();

    num id;
    String node_id;
    String name;
    String full_name;
    User owner;
    Repo parent;
    bool private;
    String html_url;
    String description;
    bool fork;
    String url;
    String archive_url;
    String assignees_url;
    String blobs_url;
    String branches_url;
    String collaborators_url;
    String comments_url;
    String commits_url;
    String compare_url;
    String contents_url;
    String contributors_url;
    String deployments_url;
    String downloads_url;
    String events_url;
    String forks_url;
    String git_commits_url;
    String git_refs_url;
    String git_tags_url;
    String git_url;
    String issue_comment_url;
    String issue_events_url;
    String issues_url;
    String keys_url;
    String labels_url;
    String languages_url;
    String merges_url;
    String milestones_url;
    String notifications_url;
    String pulls_url;
    String releases_url;
    String ssh_url;
    String stargazers_url;
    String statuses_url;
    String subscribers_url;
    String subscription_url;
    String tags_url;
    String teams_url;
    String trees_url;
    String clone_url;
    String mirror_url;
    String hooks_url;
    String svn_url;
    String homepage;
    String language;
    num forks_count;
    num stargazers_count;
    num watchers_count;
    num size;
    String default_branch;
    num open_issues_count;
    bool is_template;
    List topics;
    bool has_issues;
    bool has_projects;
    bool has_wiki;
    bool has_pages;
    bool has_downloads;
    bool archived;
    bool disabled;
    String visibility;
    String pushed_at;
    String created_at;
    String updated_at;
    Map<String,dynamic> permissions;
    bool allow_rebase_merge;
    String template_repository;
    String temp_clone_token;
    bool allow_squash_merge;
    bool allow_merge_commit;
    num subscribers_count;
    num network_count;
    Map<String,dynamic> license;
    Map<String,dynamic> organization;
    Map<String,dynamic> source;
    
    factory Repo.fromJson(Map<String,dynamic> json) => _$RepoFromJson(json);
    Map<String, dynamic> toJson() => _$RepoToJson(this);
}
